import { useState } from 'react'
import { X, Copy, Check, Download, FileText, Brain, TestTube, Code, MessageCircle } from 'lucide-react'
import ReactMarkdown from 'react-markdown'

export default function AIResultPanel({ result, action, onClose }) {
  const [copied, setCopied] = useState(false)

  if (!result) return null

  const getActionInfo = (action) => {
    switch (action) {
      case 'documentation':
        return { 
          title: 'API Documentation', 
          icon: FileText, 
          color: 'text-blue-600 dark:text-blue-400' 
        }
      case 'explain':
        return { 
          title: 'API Response Explanation', 
          icon: Brain, 
          color: 'text-purple-600 dark:text-purple-400' 
        }
      case 'testcases':
        return { 
          title: 'Test Cases', 
          icon: TestTube, 
          color: 'text-green-600 dark:text-green-400' 
        }
      case 'codesnippets':
        return { 
          title: 'Code Snippets', 
          icon: Code, 
          color: 'text-orange-600 dark:text-orange-400' 
        }
      case 'chat':
        return { 
          title: 'AI Response', 
          icon: MessageCircle, 
          color: 'text-indigo-600 dark:text-indigo-400' 
        }
      default:
        return { 
          title: 'AI Result', 
          icon: Brain, 
          color: 'text-gray-600 dark:text-gray-400' 
        }
    }
  }

  const actionInfo = getActionInfo(action)
  const Icon = actionInfo.icon

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(result)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (error) {
      console.error('Failed to copy to clipboard:', error)
    }
  }

  const downloadAsFile = () => {
    const blob = new Blob([result], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `ai-${action}-${Date.now()}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="fixed inset-0 bg-black/50 dark:bg-black/70 z-50 flex items-center justify-center p-4">
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700">
          <div className="flex items-center space-x-3">
            <div className={`p-2 rounded-lg bg-gray-100 dark:bg-gray-700 ${actionInfo.color}`}>
              <Icon className="h-5 w-5" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                {actionInfo.title}
              </h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Generated by Gemini AI
              </p>
            </div>
          </div>
          
          <div className="flex items-center space-x-2">
            <button
              onClick={copyToClipboard}
              className={`flex items-center space-x-2 px-3 py-2 text-sm rounded-lg transition-all duration-200 ${
                copied
                  ? 'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300'
                  : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
              }`}
            >
              {copied ? (
                <>
                  <Check className="h-4 w-4" />
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4" />
                  <span>Copy</span>
                </>
              )}
            </button>
            
            <button
              onClick={downloadAsFile}
              className="flex items-center space-x-2 px-3 py-2 text-sm bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-lg transition-colors"
            >
              <Download className="h-4 w-4" />
              <span>Download</span>
            </button>
            
            <button
              onClick={onClose}
              className="p-2 text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-auto p-6">
          <div className="prose prose-gray dark:prose-invert max-w-none">
            <ReactMarkdown
              components={{
                // Custom styling for code blocks
                code: ({ node, inline, className, children, ...props }) => {
                  if (inline) {
                    return (
                      <code 
                        className="px-1.5 py-0.5 bg-gray-100 dark:bg-gray-800 text-gray-800 dark:text-gray-200 rounded text-sm font-mono"
                        {...props}
                      >
                        {children}
                      </code>
                    )
                  }
                  return (
                    <pre className="bg-gray-900 dark:bg-gray-950 text-gray-100 p-4 rounded-lg overflow-x-auto">
                      <code className="text-sm font-mono" {...props}>
                        {children}
                      </code>
                    </pre>
                  )
                },
                // Custom styling for tables
                table: ({ children, ...props }) => (
                  <div className="overflow-x-auto">
                    <table className="min-w-full border border-gray-200 dark:border-gray-700" {...props}>
                      {children}
                    </table>
                  </div>
                ),
                th: ({ children, ...props }) => (
                  <th className="px-4 py-2 bg-gray-50 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 text-left font-medium text-gray-900 dark:text-white" {...props}>
                    {children}
                  </th>
                ),
                td: ({ children, ...props }) => (
                  <td className="px-4 py-2 border-b border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300" {...props}>
                    {children}
                  </td>
                ),
                // Custom styling for headings
                h1: ({ children, ...props }) => (
                  <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-4" {...props}>
                    {children}
                  </h1>
                ),
                h2: ({ children, ...props }) => (
                  <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3 mt-6" {...props}>
                    {children}
                  </h2>
                ),
                h3: ({ children, ...props }) => (
                  <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2 mt-4" {...props}>
                    {children}
                  </h3>
                ),
                // Custom styling for paragraphs
                p: ({ children, ...props }) => (
                  <p className="text-gray-700 dark:text-gray-300 mb-4 leading-relaxed" {...props}>
                    {children}
                  </p>
                ),
                // Custom styling for lists
                ul: ({ children, ...props }) => (
                  <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mb-4 space-y-1" {...props}>
                    {children}
                  </ul>
                ),
                ol: ({ children, ...props }) => (
                  <ol className="list-decimal list-inside text-gray-700 dark:text-gray-300 mb-4 space-y-1" {...props}>
                    {children}
                  </ol>
                ),
                // Custom styling for blockquotes
                blockquote: ({ children, ...props }) => (
                  <blockquote className="border-l-4 border-blue-500 pl-4 py-2 bg-blue-50 dark:bg-blue-900/20 text-blue-800 dark:text-blue-200 mb-4" {...props}>
                    {children}
                  </blockquote>
                )
              }}
            >
              {result}
            </ReactMarkdown>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
          <div className="flex items-center justify-between text-sm text-gray-500 dark:text-gray-400">
            <div>
              ⚡ Powered by Gemini AI
            </div>
            <div>
              Generated at {new Date().toLocaleTimeString()}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}