import { useState, useCallback } from 'react'
import { Copy, Check, Download, Share2, FileText } from 'lucide-react'
import { generateCurl, codeGenerators } from '../../utils/codeGenerators'

export default function CopyTools({ request, environmentVariables = {} }) {
  const [copiedItem, setCopiedItem] = useState(null)

  const copyToClipboard = useCallback(async (text, itemId) => {
    try {
      await navigator.clipboard.writeText(text)
      setCopiedItem(itemId)
      setTimeout(() => setCopiedItem(null), 2000)
    } catch (error) {
      console.error('Failed to copy to clipboard:', error)
    }
  }, [])

  const downloadAsFile = useCallback((content, filename, mimeType = 'text/plain') => {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }, [])

  const shareRequest = useCallback(async () => {
    if (!request) return

    const requestData = {
      name: request.name || 'Untitled Request',
      method: request.method,
      url: request.url,
      headers: request.headers,
      params: request.params,
      body: request.body,
      auth: request.auth
    }

    const shareText = `Request: ${requestData.name}\nMethod: ${requestData.method}\nURL: ${requestData.url}`
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Request Buddy - ${requestData.name}`,
          text: shareText,
          url: window.location.href
        })
      } catch (error) {
        console.error('Error sharing:', error)
        // Fallback to clipboard
        copyToClipboard(shareText, 'share')
      }
    } else {
      // Fallback to clipboard
      copyToClipboard(shareText, 'share')
    }
  }, [request, copyToClipboard])

  if (!request) {
    return (
      <div className="h-full flex items-center justify-center">
        <div className="text-center">
          <Copy className="h-12 w-12 text-gray-400 dark:text-gray-500 mx-auto mb-3" />
          <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">
            No Request Selected
          </h3>
          <p className="text-gray-500 dark:text-gray-400 text-sm">
            Select a request to access copy and export tools
          </p>
        </div>
      </div>
    )
  }

  const tools = [
    {
      id: 'curl',
      title: 'Copy as cURL',
      description: 'Copy request as cURL command',
      icon: Copy,
      action: () => {
        const curl = generateCurl(request, environmentVariables)
        copyToClipboard(curl, 'curl')
      }
    },
    {
      id: 'javascript',
      title: 'Copy as JavaScript',
      description: 'Copy as JavaScript fetch code',
      icon: Copy,
      action: () => {
        const code = codeGenerators.javascript(request, environmentVariables)
        copyToClipboard(code, 'javascript')
      }
    },
    {
      id: 'nodejs',
      title: 'Copy as Node.js',
      description: 'Copy as Node.js axios code',
      icon: Copy,
      action: () => {
        const code = codeGenerators.nodejs(request, environmentVariables)
        copyToClipboard(code, 'nodejs')
      }
    },
    {
      id: 'python',
      title: 'Copy as Python',
      description: 'Copy as Python requests code',
      icon: Copy,
      action: () => {
        const code = codeGenerators.python(request, environmentVariables)
        copyToClipboard(code, 'python')
      }
    },
    {
      id: 'download-curl',
      title: 'Download cURL Script',
      description: 'Download as .sh script file',
      icon: Download,
      action: () => {
        const curl = generateCurl(request, environmentVariables)
        const script = `#!/bin/bash\n\n# Generated by Request Buddy\n# ${new Date().toISOString()}\n\n${curl}\n`
        downloadAsFile(script, `${request.name || 'request'}.sh`, 'text/x-shellscript')
      }
    },
    {
      id: 'download-json',
      title: 'Export as JSON',
      description: 'Download request as JSON file',
      icon: Download,
      action: () => {
        const requestData = {
          name: request.name || 'Untitled Request',
          method: request.method,
          url: request.url,
          headers: request.headers,
          params: request.params,
          body: request.body,
          auth: request.auth,
          exportedAt: new Date().toISOString(),
          exportedBy: 'Request Buddy'
        }
        downloadAsFile(
          JSON.stringify(requestData, null, 2), 
          `${request.name || 'request'}.json`, 
          'application/json'
        )
      }
    },
    {
      id: 'share',
      title: 'Share Request',
      description: 'Share request details',
      icon: Share2,
      action: shareRequest
    }
  ]

  return (
    <div className="h-full flex flex-col">
      {/* Header */}
      <div className="p-4 border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
        <div className="flex items-center space-x-2">
          <FileText className="h-5 w-5 text-gray-600 dark:text-gray-400" />
          <h3 className="font-medium text-gray-900 dark:text-white">Copy & Export</h3>
        </div>
      </div>

      {/* Tools List */}
      <div className="flex-1 overflow-auto p-4">
        <div className="space-y-3">
          {tools.map((tool) => {
            const Icon = tool.icon
            const isCopied = copiedItem === tool.id
            
            return (
              <button
                key={tool.id}
                onClick={tool.action}
                className={`w-full flex items-center space-x-3 p-3 rounded-lg border transition-all duration-200 text-left ${
                  isCopied
                    ? 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800'
                    : 'bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700'
                }`}
              >
                <div className={`p-2 rounded-md ${
                  isCopied
                    ? 'bg-green-100 dark:bg-green-900/30'
                    : 'bg-gray-100 dark:bg-gray-700'
                }`}>
                  {isCopied ? (
                    <Check className="h-4 w-4 text-green-600 dark:text-green-400" />
                  ) : (
                    <Icon className="h-4 w-4 text-gray-600 dark:text-gray-400" />
                  )}
                </div>
                
                <div className="flex-1 min-w-0">
                  <div className={`font-medium ${
                    isCopied
                      ? 'text-green-900 dark:text-green-100'
                      : 'text-gray-900 dark:text-white'
                  }`}>
                    {isCopied ? 'Copied!' : tool.title}
                  </div>
                  <div className={`text-sm ${
                    isCopied
                      ? 'text-green-600 dark:text-green-400'
                      : 'text-gray-500 dark:text-gray-400'
                  }`}>
                    {tool.description}
                  </div>
                </div>
              </button>
            )
          })}
        </div>
      </div>

      {/* Info */}
      <div className="p-4 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
        <div className="text-xs text-gray-600 dark:text-gray-400">
          <div className="mb-1">💡 <strong>Tip:</strong> Quick copy and export tools</div>
          <div>• Environment variables are resolved automatically</div>
          <div>• Downloaded files are ready to use</div>
          <div>• Share functionality uses native sharing when available</div>
        </div>
      </div>
    </div>
  )
}