import { useState } from 'react'
import { Sparkles, ChevronDown, FileText, Brain, TestTube, Code, MessageCircle } from 'lucide-react'

export default function SimpleAIButton({ request, response, onAIAction }) {
  const [isOpen, setIsOpen] = useState(false)

  console.log("SimpleAIButton rendered with:", { hasRequest: !!request, hasResponse: !!response })

  const aiActions = [
    {
      id: 'documentation',
      label: 'Generate API Documentation',
      icon: FileText,
      description: 'Create professional API docs',
      requiresResponse: true
    },
    {
      id: 'explain',
      label: 'Explain API Response',
      icon: Brain,
      description: 'Understand what this API does',
      requiresResponse: true
    },
    {
      id: 'testcases',
      label: 'Generate Test Cases',
      icon: TestTube,
      description: 'Create comprehensive test scenarios',
      requiresResponse: true
    },
    {
      id: 'codesnippets',
      label: 'Generate Code Snippets',
      icon: Code,
      description: 'Get code examples in multiple languages',
      requiresResponse: false
    },
    {
      id: 'chat',
      label: 'Ask AI',
      icon: MessageCircle,
      description: 'Ask questions about this API',
      requiresResponse: true
    }
  ]

  const handleAction = (actionId) => {
    console.log("AI Action clicked:", actionId)
    setIsOpen(false)
    
    if (onAIAction) {
      onAIAction(actionId, request, response)
    }
  }

  return (
    <div className="relative">
      <button
        onClick={() => {
          console.log("AI Button clicked, current state:", isOpen)
          setIsOpen(!isOpen)
        }}
        className="flex items-center space-x-2 px-3 py-2 text-sm font-medium rounded-lg transition-all duration-200 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white shadow-lg hover:shadow-xl"
        title="AI Assistant"
      >
        <Sparkles className="h-4 w-4" />
        <span>AI Assistant</span>
        <ChevronDown className="h-4 w-4" />
      </button>

      {/* Dropdown Menu */}
      {isOpen && (
        <div className="absolute top-full right-0 mt-2 w-80 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-xl z-50">
          <div className="p-3 border-b border-gray-200 dark:border-gray-700">
            <h3 className="font-medium text-gray-900 dark:text-white">AI Assistant</h3>
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
              Choose an AI action to help with your API
            </p>
          </div>
          
          <div className="py-2">
            {aiActions.map((action) => {
              const Icon = action.icon
              const isDisabled = action.requiresResponse && !response
              
              return (
                <button
                  key={action.id}
                  onClick={() => handleAction(action.id)}
                  disabled={isDisabled}
                  className={`w-full flex items-start space-x-3 px-4 py-3 text-left transition-colors ${
                    isDisabled
                      ? 'text-gray-400 dark:text-gray-500 cursor-not-allowed'
                      : 'text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700'
                  }`}
                >
                  <Icon className="h-5 w-5 mt-0.5 flex-shrink-0" />
                  <div className="min-w-0 flex-1">
                    <div className="font-medium">{action.label}</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">
                      {action.description}
                      {isDisabled && ' (requires response)'}
                    </div>
                  </div>
                </button>
              )
            })}
          </div>
          
          <div className="p-3 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
            <div className="text-xs text-gray-500 dark:text-gray-400">
              💡 AI responses are generated by Gemini and may not always be accurate
            </div>
          </div>
        </div>
      )}

      {/* Click outside to close */}
      {isOpen && (
        <div 
          className="fixed inset-0 z-40" 
          onClick={() => setIsOpen(false)}
        />
      )}
    </div>
  )
}